version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:30"
    commit-message:
      prefix: "fix"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
