name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-merge Dependabot PR
        if: github.actor == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository
        uses: actions-ecosystem/action-merge-dependabot@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
